### ISSUE TITLE
guidance on how to keep distributions

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#175]
at iso1913 exports all my distributions get 'lost'

i was looking at this code
https://github.com/geopython/pygeometa/blob/253a78fdd4594df0dbce127d3d3c1b2407511897/pygeometa/core.py#L208-L219

i don't see how language would be a part of nil_reasons as suggested there

**Comment by tomkralidis** [comment]
@pvgenuchten thanks for the report. Fixed in #191.  The reason why distributions were not showing up was because pygeometa was expecting distribution keys to have the language as part of the key name (this is for the ISO HNAP case/rendering).  We don't need this kind of magic for anything that is not HNAP.
