### ISSUE TITLE
Autolaunch of post-processing script

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#64]
Feature request for the capability to specify a post-processing script to be ran after pygeometa is done generating the output xml. The post-processing script could be invoked with ```--postprocessing=script-name.py```. The pygeometa arguments would be sent to the post-processing script, which could thus identified which input mcf file has been specified and which output xml file has been generated.

Usage example: this would allow pygeometa to automatically launch Python scripts to apply processing which is not within pygeometa's scope. This post-processing capability could be used in conjunction with the batch mode (feature request in #63).

In a future version, the ```--postprocessing``` argument could also write in the pygeometa log.

Thoughts on the pertinence of this feature request?

**Comment by tomkralidis** [comment]
I'd rather delegate this functionality downstream so that pygeometa continues to follow the [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) (do one thing and do it well).

Suggested approaches:

- build your own Python script which uses pygeometa as a library for a custom workflow
- pipes: pygeometa outputs to file (via `--output`) or to `stdout` by default.  So one can run something like:

```bash
pygeometa generate_metadata --mcf=foo.yml --schema=iso19139 | somescript # script reads stdin
```

**Comment by alexandreleroux** [comment]
Agreed. Thanks for the feedback @tomkralidis
